framework: jest
preRun:
  command:
    - yarn install
preMerge:
  env:
    TZ: UTC
  pattern:
    - "./**/__tests__/*.test.{js,ts,tsx}"
postMerge:
  env:
    TZ: UTC
  pattern:
    - "./**/__tests__/*.test.{js,ts,tsx}"
postRun:
  command:
    - yarn --version
version: 1.0
